// Generated by Xata Codegen 0.22.3. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  { name: "votes", columns: [{ name: "vote", type: "string" }] },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Votes = InferredTypes["votes"];
export type VotesRecord = Votes & XataRecord;

export type DatabaseSchema = {
  votes: VotesRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL: "https://lindgr3n-lhrlkl.eu-west-1.xata.sh/db/my-app",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
